#Meriones Makefile

#prelozi projekt vcetne programu pro profilling
all: 

#zabali projekt tak aby mohl byt odevzdan
pack:

#smazen vsechny soubory, co nemaji byt odevzdany
clean:

#spusti testy matematicke knihovny
test:

#spusti generovani dokumentace
doc:

#spusti program
run:
