#Meriones Makefile

.PHONY: all pack clean test doc run

#prelozi projekt vcetne programu pro profilling
all: 

init:
    pip install -r requirements.txt
    
#zabali projekt tak aby mohl byt odevzdan
pack:

#smazen vsechny soubory, co nemaji byt odevzdany
clean:

#spusti testy matematicke knihovny
test: ../tests/merioneslib_tests.py
    python3 merioneslib_tests.py

#spusti generovani dokumentace
doc:

#spusti program
run: main.py
    python3 main.py
